os: osx
language: generic
osx_image: xcode9.4
before_script:
  - brew update
  - brew install yasm
script:
  - ./init-ios-openssl.sh arm64
  - ./init-ios.sh arm64
  - cd ios
  - ./compile-openssl.sh clean
  - ./compile-ffmpeg.sh clean
  - ./compile-openssl.sh arm64
  - ./compile-ffmpeg.sh arm64
  - git status
