os: osx
language: generic
osx_image: xcode9.4
env:
  -ARCHIVE_PATH="Runner.xcarchive"
  -PARENT="1BPIKK7sxbfdDu59wKmp3dl83lXpTkHRJ"
before_script:
  - brew update
  - brew install gdrive
  - brew install yasm
script:
  - ./init-ios-openssl.sh arm64
  - ./init-ios.sh arm64
  - cd ios
  - ./compile-openssl.sh clean
  - ./compile-ffmpeg.sh clean
  - ./compile-openssl.sh arm64
  - ./compile-ffmpeg.sh arm64
  # - gdrive upload --refresh-token ${REFRESH_TOKEN} --parent ${PARENT} ${ARCHIVE_PATH} 
  
