os: osx
language: generic
osx_image: xcode9.4
env:
  -BUILD_DIR="ios/build"
  -OUTPUT_DIR="ios/IJKMediaPlayer/ios/build/Release-iphoneos/IJKMediaFramework.framework"
  -PARENT="1BPIKK7sxbfdDu59wKmp3dl83lXpTkHRJ"
before_script:
  - brew update
  - brew install gdrive
  - brew install yasm
script:
  - ./travis-run.sh 
  - xcodebuild build -project ios/IJKMediaDemo/IJKMediaDemo.xcodeproj -scheme IJKMediaFramework -configuration Release -sdk iphoneos VALID_ARCHS=arm64 BUILD_DIR=${BUILD_DIR} | xcpretty
  - find . | grep framework
  - du -sh * ${OUTPUT_DIR}
  - gdrive upload --recursive --refresh-token ${REFRESH_TOKEN} --parent ${PARENT} ${OUTPUT_DIR}
