os: osx
language: generic
osx_image: xcode9.4
env:
  -ARCHIVE_PATH="Runner.xcarchive"
  -PARENT="1BPIKK7sxbfdDu59wKmp3dl83lXpTkHRJ"
before_script:
  - brew update
  - brew install gdrive
  - brew install yasm
script:
  - ./travis-run.sh 
  # - gdrive upload --refresh-token ${REFRESH_TOKEN} --parent ${PARENT} ${ARCHIVE_PATH}   
