os: osx
language: generic
osx_image: xcode9.4
env:
  -BUILD_DIR="/Users/travis/build/anykao/ijkplayer-ios/ios/build"
  -PARENT="1BPIKK7sxbfdDu59wKmp3dl83lXpTkHRJ"
before_script:
  - brew update
  - brew install gdrive
  - brew install yasm
script:
  - ./travis-run.sh 
  - xcodebuild build -project ios/IJKMediaDemo/IJKMediaDemo.xcodeproj -scheme IJKMediaFramework -configuration Release -sdk iphoneos VALID_ARCHS=arm64 BUILD_DIR=${BUILD_DIR} | xcpretty
  - du -sh * ${BUILD_DIR}/build
  - ls -lh ${BUILD_DIR}/build/IJKMediaFramework.framework
  - ls -lh ${BUILD_DIR}/build/IJKMediaPlayer/IJKMediaFramework.framework
  - gdrive upload --recursive --refresh-token ${REFRESH_TOKEN} --parent ${PARENT} ${BUILD_DIR}/IJKMediaFramework.framework
